[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

# Single Page App fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
